// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/subnet/gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GossipMessage is the top-level message for gossip protocol
type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GossipMessage_Signature
	Payload       isGossipMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_subnet_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_subnet_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessage) GetPayload() isGossipMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GossipMessage) GetSignature() *CheckpointSignature {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_Signature); ok {
			return x.Signature
		}
	}
	return nil
}

type isGossipMessage_Payload interface {
	isGossipMessage_Payload()
}

type GossipMessage_Signature struct {
	Signature *CheckpointSignature `protobuf:"bytes,1,opt,name=signature,proto3,oneof"`
}

func (*GossipMessage_Signature) isGossipMessage_Payload() {}

// CheckpointSignature contains a validator's signature on a checkpoint
type CheckpointSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Epoch of the checkpoint being signed
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Validator ID who signed this checkpoint
	ValidatorId string `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	// DER-encoded ECDSA signature
	SignatureDer []byte `protobuf:"bytes,3,opt,name=signature_der,json=signatureDer,proto3" json:"signature_der,omitempty"`
	// Unix timestamp when signature was created
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Hash of the checkpoint header to prevent signing wrong checkpoint
	CheckpointHash []byte `protobuf:"bytes,5,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointSignature) Reset() {
	*x = CheckpointSignature{}
	mi := &file_proto_subnet_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointSignature) ProtoMessage() {}

func (x *CheckpointSignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointSignature.ProtoReflect.Descriptor instead.
func (*CheckpointSignature) Descriptor() ([]byte, []int) {
	return file_proto_subnet_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointSignature) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CheckpointSignature) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *CheckpointSignature) GetSignatureDer() []byte {
	if x != nil {
		return x.SignatureDer
	}
	return nil
}

func (x *CheckpointSignature) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CheckpointSignature) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

var File_proto_subnet_gossip_proto protoreflect.FileDescriptor

const file_proto_subnet_gossip_proto_rawDesc = "" +
	"\n" +
	"\x19proto/subnet/gossip.proto\x12\tsubnet.v1\"Z\n" +
	"\rGossipMessage\x12>\n" +
	"\tsignature\x18\x01 \x01(\v2\x1e.subnet.v1.CheckpointSignatureH\x00R\tsignatureB\t\n" +
	"\apayload\"\xba\x01\n" +
	"\x13CheckpointSignature\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12#\n" +
	"\rsignature_der\x18\x03 \x01(\fR\fsignatureDer\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fcheckpoint_hash\x18\x05 \x01(\fR\x0echeckpointHashB\x18Z\x16subnet/proto/subnet;pbb\x06proto3"

var (
	file_proto_subnet_gossip_proto_rawDescOnce sync.Once
	file_proto_subnet_gossip_proto_rawDescData []byte
)

func file_proto_subnet_gossip_proto_rawDescGZIP() []byte {
	file_proto_subnet_gossip_proto_rawDescOnce.Do(func() {
		file_proto_subnet_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subnet_gossip_proto_rawDesc), len(file_proto_subnet_gossip_proto_rawDesc)))
	})
	return file_proto_subnet_gossip_proto_rawDescData
}

var file_proto_subnet_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_subnet_gossip_proto_goTypes = []any{
	(*GossipMessage)(nil),       // 0: subnet.v1.GossipMessage
	(*CheckpointSignature)(nil), // 1: subnet.v1.CheckpointSignature
}
var file_proto_subnet_gossip_proto_depIdxs = []int32{
	1, // 0: subnet.v1.GossipMessage.signature:type_name -> subnet.v1.CheckpointSignature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subnet_gossip_proto_init() }
func file_proto_subnet_gossip_proto_init() {
	if File_proto_subnet_gossip_proto != nil {
		return
	}
	file_proto_subnet_gossip_proto_msgTypes[0].OneofWrappers = []any{
		(*GossipMessage_Signature)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subnet_gossip_proto_rawDesc), len(file_proto_subnet_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_subnet_gossip_proto_goTypes,
		DependencyIndexes: file_proto_subnet_gossip_proto_depIdxs,
		MessageInfos:      file_proto_subnet_gossip_proto_msgTypes,
	}.Build()
	File_proto_subnet_gossip_proto = out.File
	file_proto_subnet_gossip_proto_goTypes = nil
	file_proto_subnet_gossip_proto_depIdxs = nil
}
