// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/common/types.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一错误码 - 与API规范保持一致
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_SUCCESS                ErrorCode = 1
	ErrorCode_INVALID_REQUEST        ErrorCode = 2
	ErrorCode_UNAUTHORIZED           ErrorCode = 3
	ErrorCode_FORBIDDEN              ErrorCode = 4
	ErrorCode_NOT_FOUND              ErrorCode = 5
	ErrorCode_CONFLICT               ErrorCode = 6
	ErrorCode_INTERNAL_ERROR         ErrorCode = 7
	ErrorCode_SERVICE_UNAVAILABLE    ErrorCode = 8
	ErrorCode_RATE_LIMITED           ErrorCode = 9
	// Intent相关错误 (2000-2099)
	ErrorCode_INTENT_EXISTS       ErrorCode = 2001
	ErrorCode_INTENT_NOT_FOUND    ErrorCode = 2002
	ErrorCode_INTENT_EXPIRED      ErrorCode = 2003
	ErrorCode_INVALID_INTENT_TYPE ErrorCode = 2004
	ErrorCode_INVALID_BUDGET      ErrorCode = 2005
	ErrorCode_INVALID_DEADLINE    ErrorCode = 2006
	ErrorCode_INVALID_SIGNATURE   ErrorCode = 2007
	ErrorCode_SUBNET_NOT_FOUND    ErrorCode = 2008
	ErrorCode_SUBNET_INACTIVE     ErrorCode = 2009
	// Bid相关错误 (2100-2199)
	ErrorCode_BID_EXISTS          ErrorCode = 2101
	ErrorCode_BID_NOT_FOUND       ErrorCode = 2102
	ErrorCode_BIDDING_CLOSED      ErrorCode = 2103
	ErrorCode_PRICE_TOO_HIGH      ErrorCode = 2104
	ErrorCode_PRICE_TOO_LOW       ErrorCode = 2105
	ErrorCode_INVALID_QOS_PARAMS  ErrorCode = 2106
	ErrorCode_AGENT_NOT_QUALIFIED ErrorCode = 2107
	// WebSocket相关错误 (3000-3099)
	ErrorCode_WS_AUTH_FAILED      ErrorCode = 3001
	ErrorCode_WS_CONNECTION_LIMIT ErrorCode = 3002
	ErrorCode_WS_INVALID_MESSAGE  ErrorCode = 3003
	ErrorCode_WS_CLIENT_NOT_FOUND ErrorCode = 3004
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_CODE_UNSPECIFIED",
		1:    "SUCCESS",
		2:    "INVALID_REQUEST",
		3:    "UNAUTHORIZED",
		4:    "FORBIDDEN",
		5:    "NOT_FOUND",
		6:    "CONFLICT",
		7:    "INTERNAL_ERROR",
		8:    "SERVICE_UNAVAILABLE",
		9:    "RATE_LIMITED",
		2001: "INTENT_EXISTS",
		2002: "INTENT_NOT_FOUND",
		2003: "INTENT_EXPIRED",
		2004: "INVALID_INTENT_TYPE",
		2005: "INVALID_BUDGET",
		2006: "INVALID_DEADLINE",
		2007: "INVALID_SIGNATURE",
		2008: "SUBNET_NOT_FOUND",
		2009: "SUBNET_INACTIVE",
		2101: "BID_EXISTS",
		2102: "BID_NOT_FOUND",
		2103: "BIDDING_CLOSED",
		2104: "PRICE_TOO_HIGH",
		2105: "PRICE_TOO_LOW",
		2106: "INVALID_QOS_PARAMS",
		2107: "AGENT_NOT_QUALIFIED",
		3001: "WS_AUTH_FAILED",
		3002: "WS_CONNECTION_LIMIT",
		3003: "WS_INVALID_MESSAGE",
		3004: "WS_CLIENT_NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"SUCCESS":                1,
		"INVALID_REQUEST":        2,
		"UNAUTHORIZED":           3,
		"FORBIDDEN":              4,
		"NOT_FOUND":              5,
		"CONFLICT":               6,
		"INTERNAL_ERROR":         7,
		"SERVICE_UNAVAILABLE":    8,
		"RATE_LIMITED":           9,
		"INTENT_EXISTS":          2001,
		"INTENT_NOT_FOUND":       2002,
		"INTENT_EXPIRED":         2003,
		"INVALID_INTENT_TYPE":    2004,
		"INVALID_BUDGET":         2005,
		"INVALID_DEADLINE":       2006,
		"INVALID_SIGNATURE":      2007,
		"SUBNET_NOT_FOUND":       2008,
		"SUBNET_INACTIVE":        2009,
		"BID_EXISTS":             2101,
		"BID_NOT_FOUND":          2102,
		"BIDDING_CLOSED":         2103,
		"PRICE_TOO_HIGH":         2104,
		"PRICE_TOO_LOW":          2105,
		"INVALID_QOS_PARAMS":     2106,
		"AGENT_NOT_QUALIFIED":    2107,
		"WS_AUTH_FAILED":         3001,
		"WS_CONNECTION_LIMIT":    3002,
		"WS_INVALID_MESSAGE":     3003,
		"WS_CLIENT_NOT_FOUND":    3004,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_types_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_common_types_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{0}
}

// Common priority levels
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_types_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_common_types_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{1}
}

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	ServiceStatus_SERVICE_HEALTHY            ServiceStatus = 1
	ServiceStatus_SERVICE_DEGRADED           ServiceStatus = 2
	ServiceStatus_SERVICE_UNHEALTHY          ServiceStatus = 3
	ServiceStatus_SERVICE_MAINTENANCE        ServiceStatus = 4
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_HEALTHY",
		2: "SERVICE_DEGRADED",
		3: "SERVICE_UNHEALTHY",
		4: "SERVICE_MAINTENANCE",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_HEALTHY":            1,
		"SERVICE_DEGRADED":           2,
		"SERVICE_UNHEALTHY":          3,
		"SERVICE_MAINTENANCE":        4,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_types_proto_enumTypes[2].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_proto_common_types_proto_enumTypes[2]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{2}
}

// Common acknowledgment message used across services
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"` // optional transaction hash
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`        // operation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Ack) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Ack) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 分页请求 - 与API规范保持一致
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 页大小
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`     // 排序字段
	OrderDir      string                 `protobuf:"bytes,4,opt,name=order_dir,json=orderDir,proto3" json:"order_dir,omitempty"`  // 排序方向
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_proto_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *PageRequest) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

// 分页响应
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                             // 总数
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                               // 当前页
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 页大小
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // 总页数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_proto_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Common error types
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=common.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Cryptographic signatures
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          string                 `protobuf:"bytes,1,opt,name=algo,proto3" json:"algo,omitempty"`                         // "ECDSA-secp256k1", "BLS12-381"
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                         // signature bytes
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                     // public key
	SignerId      string                 `protobuf:"bytes,4,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"` // signer identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_common_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{4}
}

func (x *Signature) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *Signature) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Signature) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Signature) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

// Multi-signature
type MultiSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    []*Signature           `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Bitmap        []byte                 `protobuf:"bytes,2,opt,name=bitmap,proto3" json:"bitmap,omitempty"`        // signers bitmap for efficiency
	Threshold     uint32                 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"` // required signatures
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSig) Reset() {
	*x = MultiSig{}
	mi := &file_proto_common_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSig) ProtoMessage() {}

func (x *MultiSig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSig.ProtoReflect.Descriptor instead.
func (*MultiSig) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{5}
}

func (x *MultiSig) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *MultiSig) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *MultiSig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// Merkle proof
type MerkleProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaf          []byte                 `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`                             // leaf data
	LeafIndex     uint32                 `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"` // position in tree
	Siblings      [][]byte               `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`                     // sibling hashes
	Root          []byte                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`                             // merkle root
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProof) Reset() {
	*x = MerkleProof{}
	mi := &file_proto_common_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProof) ProtoMessage() {}

func (x *MerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProof.ProtoReflect.Descriptor instead.
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{6}
}

func (x *MerkleProof) GetLeaf() []byte {
	if x != nil {
		return x.Leaf
	}
	return nil
}

func (x *MerkleProof) GetLeafIndex() uint32 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *MerkleProof) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *MerkleProof) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Time range
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // unix timestamp
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_proto_common_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{7}
}

func (x *TimeRange) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeRange) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

// Resource limits
type ResourceLimits struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxCpuMs        uint64                 `protobuf:"varint,1,opt,name=max_cpu_ms,json=maxCpuMs,proto3" json:"max_cpu_ms,omitempty"`
	MaxMemoryMb     uint64                 `protobuf:"varint,2,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	MaxStorageMb    uint64                 `protobuf:"varint,3,opt,name=max_storage_mb,json=maxStorageMb,proto3" json:"max_storage_mb,omitempty"`
	MaxNetworkBytes uint64                 `protobuf:"varint,4,opt,name=max_network_bytes,json=maxNetworkBytes,proto3" json:"max_network_bytes,omitempty"`
	MaxDurationSec  uint32                 `protobuf:"varint,5,opt,name=max_duration_sec,json=maxDurationSec,proto3" json:"max_duration_sec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_common_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceLimits) GetMaxCpuMs() uint64 {
	if x != nil {
		return x.MaxCpuMs
	}
	return 0
}

func (x *ResourceLimits) GetMaxMemoryMb() uint64 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetMaxStorageMb() uint64 {
	if x != nil {
		return x.MaxStorageMb
	}
	return 0
}

func (x *ResourceLimits) GetMaxNetworkBytes() uint64 {
	if x != nil {
		return x.MaxNetworkBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxDurationSec() uint32 {
	if x != nil {
		return x.MaxDurationSec
	}
	return 0
}

// Key-value metadata
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]string      `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_common_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{9}
}

func (x *Metadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Metadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Metadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Domain-separated hash for different contexts
type DomainHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"` // e.g., "intent:v1", "bid:v1"
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"` // computed hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainHash) Reset() {
	*x = DomainHash{}
	mi := &file_proto_common_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainHash) ProtoMessage() {}

func (x *DomainHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainHash.ProtoReflect.Descriptor instead.
func (*DomainHash) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{10}
}

func (x *DomainHash) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainHash) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DomainHash) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DomainHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Health status
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ServiceStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastCheck     int64                  `protobuf:"varint,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_common_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_common_types_proto_rawDescGZIP(), []int{11}
}

func (x *HealthStatus) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthStatus) GetLastCheck() int64 {
	if x != nil {
		return x.LastCheck
	}
	return 0
}

var File_proto_common_types_proto protoreflect.FileDescriptor

const file_proto_common_types_proto_rawDesc = "" +
	"\n" +
	"\x18proto/common/types.proto\x12\tcommon.v1\"^\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"v\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x1b\n" +
	"\torder_dir\x18\x04 \x01(\tR\borderDir\"v\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xc0\x01\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\adetails\x18\x03 \x03(\v2\x1d.common.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\tSignature\x12\x12\n" +
	"\x04algo\x18\x01 \x01(\tR\x04algo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06pubkey\x18\x03 \x01(\fR\x06pubkey\x12\x1b\n" +
	"\tsigner_id\x18\x04 \x01(\tR\bsignerId\"v\n" +
	"\bMultiSig\x124\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2\x14.common.v1.SignatureR\n" +
	"signatures\x12\x16\n" +
	"\x06bitmap\x18\x02 \x01(\fR\x06bitmap\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\"p\n" +
	"\vMerkleProof\x12\x12\n" +
	"\x04leaf\x18\x01 \x01(\fR\x04leaf\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x02 \x01(\rR\tleafIndex\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04root\x18\x04 \x01(\fR\x04root\"3\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\xce\x01\n" +
	"\x0eResourceLimits\x12\x1c\n" +
	"\n" +
	"max_cpu_ms\x18\x01 \x01(\x04R\bmaxCpuMs\x12\"\n" +
	"\rmax_memory_mb\x18\x02 \x01(\x04R\vmaxMemoryMb\x12$\n" +
	"\x0emax_storage_mb\x18\x03 \x01(\x04R\fmaxStorageMb\x12*\n" +
	"\x11max_network_bytes\x18\x04 \x01(\x04R\x0fmaxNetworkBytes\x12(\n" +
	"\x10max_duration_sec\x18\x05 \x01(\rR\x0emaxDurationSec\"\xcc\x01\n" +
	"\bMetadata\x12C\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2#.common.v1.Metadata.AttributesEntryR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\n" +
	"DomainHash\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\"\xf5\x01\n" +
	"\fHealthStatus\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.common.v1.ServiceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.common.v1.HealthStatus.DetailsEntryR\adetails\x12\x1d\n" +
	"\n" +
	"last_check\x18\x04 \x01(\x03R\tlastCheck\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x89\x05\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x02\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x03\x12\r\n" +
	"\tFORBIDDEN\x10\x04\x12\r\n" +
	"\tNOT_FOUND\x10\x05\x12\f\n" +
	"\bCONFLICT\x10\x06\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\a\x12\x17\n" +
	"\x13SERVICE_UNAVAILABLE\x10\b\x12\x10\n" +
	"\fRATE_LIMITED\x10\t\x12\x12\n" +
	"\rINTENT_EXISTS\x10\xd1\x0f\x12\x15\n" +
	"\x10INTENT_NOT_FOUND\x10\xd2\x0f\x12\x13\n" +
	"\x0eINTENT_EXPIRED\x10\xd3\x0f\x12\x18\n" +
	"\x13INVALID_INTENT_TYPE\x10\xd4\x0f\x12\x13\n" +
	"\x0eINVALID_BUDGET\x10\xd5\x0f\x12\x15\n" +
	"\x10INVALID_DEADLINE\x10\xd6\x0f\x12\x16\n" +
	"\x11INVALID_SIGNATURE\x10\xd7\x0f\x12\x15\n" +
	"\x10SUBNET_NOT_FOUND\x10\xd8\x0f\x12\x14\n" +
	"\x0fSUBNET_INACTIVE\x10\xd9\x0f\x12\x0f\n" +
	"\n" +
	"BID_EXISTS\x10\xb5\x10\x12\x12\n" +
	"\rBID_NOT_FOUND\x10\xb6\x10\x12\x13\n" +
	"\x0eBIDDING_CLOSED\x10\xb7\x10\x12\x13\n" +
	"\x0ePRICE_TOO_HIGH\x10\xb8\x10\x12\x12\n" +
	"\rPRICE_TOO_LOW\x10\xb9\x10\x12\x17\n" +
	"\x12INVALID_QOS_PARAMS\x10\xba\x10\x12\x18\n" +
	"\x13AGENT_NOT_QUALIFIED\x10\xbb\x10\x12\x13\n" +
	"\x0eWS_AUTH_FAILED\x10\xb9\x17\x12\x18\n" +
	"\x13WS_CONNECTION_LIMIT\x10\xba\x17\x12\x17\n" +
	"\x12WS_INVALID_MESSAGE\x10\xbb\x17\x12\x18\n" +
	"\x13WS_CLIENT_NOT_FOUND\x10\xbc\x17*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*\x8a\x01\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSERVICE_HEALTHY\x10\x01\x12\x14\n" +
	"\x10SERVICE_DEGRADED\x10\x02\x12\x15\n" +
	"\x11SERVICE_UNHEALTHY\x10\x03\x12\x17\n" +
	"\x13SERVICE_MAINTENANCE\x10\x04B\x17Z\x15common/proto;commonpbb\x06proto3"

var (
	file_proto_common_types_proto_rawDescOnce sync.Once
	file_proto_common_types_proto_rawDescData []byte
)

func file_proto_common_types_proto_rawDescGZIP() []byte {
	file_proto_common_types_proto_rawDescOnce.Do(func() {
		file_proto_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_types_proto_rawDesc), len(file_proto_common_types_proto_rawDesc)))
	})
	return file_proto_common_types_proto_rawDescData
}

var file_proto_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_common_types_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: common.v1.ErrorCode
	(Priority)(0),          // 1: common.v1.Priority
	(ServiceStatus)(0),     // 2: common.v1.ServiceStatus
	(*Ack)(nil),            // 3: common.v1.Ack
	(*PageRequest)(nil),    // 4: common.v1.PageRequest
	(*PageResponse)(nil),   // 5: common.v1.PageResponse
	(*Error)(nil),          // 6: common.v1.Error
	(*Signature)(nil),      // 7: common.v1.Signature
	(*MultiSig)(nil),       // 8: common.v1.MultiSig
	(*MerkleProof)(nil),    // 9: common.v1.MerkleProof
	(*TimeRange)(nil),      // 10: common.v1.TimeRange
	(*ResourceLimits)(nil), // 11: common.v1.ResourceLimits
	(*Metadata)(nil),       // 12: common.v1.Metadata
	(*DomainHash)(nil),     // 13: common.v1.DomainHash
	(*HealthStatus)(nil),   // 14: common.v1.HealthStatus
	nil,                    // 15: common.v1.Error.DetailsEntry
	nil,                    // 16: common.v1.Metadata.AttributesEntry
	nil,                    // 17: common.v1.HealthStatus.DetailsEntry
}
var file_proto_common_types_proto_depIdxs = []int32{
	0,  // 0: common.v1.Error.code:type_name -> common.v1.ErrorCode
	15, // 1: common.v1.Error.details:type_name -> common.v1.Error.DetailsEntry
	7,  // 2: common.v1.MultiSig.signatures:type_name -> common.v1.Signature
	16, // 3: common.v1.Metadata.attributes:type_name -> common.v1.Metadata.AttributesEntry
	2,  // 4: common.v1.HealthStatus.status:type_name -> common.v1.ServiceStatus
	17, // 5: common.v1.HealthStatus.details:type_name -> common.v1.HealthStatus.DetailsEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_common_types_proto_init() }
func file_proto_common_types_proto_init() {
	if File_proto_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_types_proto_rawDesc), len(file_proto_common_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_types_proto_goTypes,
		DependencyIndexes: file_proto_common_types_proto_depIdxs,
		EnumInfos:         file_proto_common_types_proto_enumTypes,
		MessageInfos:      file_proto_common_types_proto_msgTypes,
	}.Build()
	File_proto_common_types_proto = out.File
	file_proto_common_types_proto_goTypes = nil
	file_proto_common_types_proto_depIdxs = nil
}
