# Configuration with NATS enabled for P2P networking

subnet_id: "subnet-1"

validator_set:
  min_validators: 4
  threshold_num: 3
  threshold_denom: 4
  validators:
    - id: "v1"
      endpoint: "127.0.0.1:7001"
    - id: "v2"
      endpoint: "127.0.0.1:7002"
    - id: "v3"
      endpoint: "127.0.0.1:7003"
    - id: "v4"
      endpoint: "127.0.0.1:7004"

consensus:
  propose_timeout_ms: 1500
  collect_timeout_ms: 2000
  challenge_window_ms: 300000

storage:
  leveldb_path: "./data/validator.db"

rpc:
  listen_addr: "0.0.0.0:8080"
  auth:
    enabled: false
    bearer_tokens: []

metrics:
  enabled: true
  listen_addr: "0.0.0.0:9090"

# NATS configuration for P2P networking
nats:
  url: "nats://localhost:4222"
  subject_propose: "checkpoint.propose"
  subject_signature: "checkpoint.signature"
  subject_finalized: "checkpoint.finalized"
  dedupe_ttl_seconds: 60
  dedupe_max: 10000

# Recovery mode
recovery:
  mode: "simple"  # Options: none, simple, full

# Demo signers for testing (DO NOT USE IN PRODUCTION)
demo_signers:
  - id: "v1"
    privkey_hex: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  - id: "v2"
    privkey_hex: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
  - id: "v3"
    privkey_hex: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
  - id: "v4"
    privkey_hex: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"